/* Generated By:JavaCC: Do not edit this line. GrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int skip = 1;
  /** RegularExpression Id. */
  int element = 2;
  /** RegularExpression Id. */
  int create = 3;
  /** RegularExpression Id. */
  int img = 4;
  /** RegularExpression Id. */
  int header = 5;
  /** RegularExpression Id. */
  int para = 6;
  /** RegularExpression Id. */
  int url = 7;
  /** RegularExpression Id. */
  int decorated_url = 8;
  /** RegularExpression Id. */
  int decorated_text = 9;
  /** RegularExpression Id. */
  int text = 10;
  /** RegularExpression Id. */
  int color = 11;
  /** RegularExpression Id. */
  int font = 12;
  /** RegularExpression Id. */
  int link = 13;
  /** RegularExpression Id. */
  int URL = 14;
  /** RegularExpression Id. */
  int quote = 15;
  /** RegularExpression Id. */
  int alphanumeric = 16;
  /** RegularExpression Id. */
  int sentence = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<skip>",
    "<element>",
    "<create>",
    "<img>",
    "<header>",
    "<para>",
    "<url>",
    "<decorated_url>",
    "<decorated_text>",
    "<text>",
    "<color>",
    "<font>",
    "<link>",
    "<URL>",
    "\"\\\"\"",
    "<alphanumeric>",
    "<sentence>",
  };

}
