package com.company;
/* GrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. GrammarTokenManager.java */

/** Token Manager. */
public class GrammarTokenManager implements GrammarConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
static private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(504, 0);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 505;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddStates(0, 4); }
                  break;
               case 3:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(3, 22); }
                  break;
               case 5:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(5, 18); }
                  break;
               case 7:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 8:
                  if (curChar == 34)
                     { jjCheckNAdd(9); }
                  break;
               case 9:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 11:
                  if ((0x100002200L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  { jjCheckNAdd(11); }
                  break;
               case 12:
                  if (curChar == 10 && kind > 3)
                     kind = 3;
                  break;
               case 13:
                  if (curChar == 10)
                     { jjCheckNAdd(8); }
                  break;
               case 19:
                  if (curChar == 10)
                     { jjCheckNAdd(18); }
                  break;
               case 23:
                  if (curChar == 10)
                     { jjCheckNAdd(22); }
                  break;
               case 29:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(29, 30); }
                  break;
               case 32:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(32, 138); }
                  break;
               case 34:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 35:
                  if (curChar == 34)
                     { jjCheckNAdd(36); }
                  break;
               case 36:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(36, 37); }
                  break;
               case 37:
                  if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 38:
                  if ((0x100002200L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  { jjCheckNAdd(38); }
                  break;
               case 39:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(134, 96); }
                  break;
               case 41:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(41, 42); }
                  break;
               case 44:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(44, 101); }
                  break;
               case 46:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 47:
                  if (curChar == 34)
                     { jjCheckNAdd(48); }
                  break;
               case 48:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 49:
                  if (curChar == 34)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 51:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(51, 52); }
                  break;
               case 54:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(54, 63); }
                  break;
               case 56:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(56, 57); }
                  break;
               case 57:
                  if (curChar == 34)
                     { jjCheckNAdd(58); }
                  break;
               case 58:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(58, 59); }
                  break;
               case 59:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(38, 12); }
                  break;
               case 60:
                  if (curChar == 10)
                     { jjCheckNAdd(57); }
                  break;
               case 64:
                  if (curChar == 10)
                     { jjCheckNAdd(63); }
                  break;
               case 68:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(68, 77); }
                  break;
               case 70:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(70, 71); }
                  break;
               case 71:
                  if (curChar == 34)
                     { jjCheckNAdd(72); }
                  break;
               case 72:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(72, 59); }
                  break;
               case 73:
                  if (curChar == 10)
                     { jjCheckNAdd(71); }
                  break;
               case 78:
                  if (curChar == 10)
                     { jjCheckNAdd(77); }
                  break;
               case 82:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(82, 90); }
                  break;
               case 84:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(84, 85); }
                  break;
               case 85:
                  if (curChar == 34)
                     { jjCheckNAdd(86); }
                  break;
               case 86:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(86, 59); }
                  break;
               case 87:
                  if (curChar == 10)
                     { jjCheckNAdd(85); }
                  break;
               case 91:
                  if (curChar == 10)
                     { jjCheckNAdd(90); }
                  break;
               case 94:
                  if (curChar == 10)
                     { jjCheckNAdd(52); }
                  break;
               case 97:
                  if (curChar == 32)
                     { jjCheckNAdd(96); }
                  break;
               case 98:
                  if (curChar == 10)
                     { jjCheckNAdd(47); }
                  break;
               case 102:
                  if (curChar == 10)
                     { jjCheckNAdd(101); }
                  break;
               case 106:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(106, 115); }
                  break;
               case 108:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(108, 109); }
                  break;
               case 109:
                  if (curChar == 34)
                     { jjCheckNAdd(110); }
                  break;
               case 110:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(110, 49); }
                  break;
               case 111:
                  if (curChar == 10)
                     { jjCheckNAdd(109); }
                  break;
               case 116:
                  if (curChar == 10)
                     { jjCheckNAdd(115); }
                  break;
               case 120:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(120, 128); }
                  break;
               case 122:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(122, 123); }
                  break;
               case 123:
                  if (curChar == 34)
                     { jjCheckNAdd(124); }
                  break;
               case 124:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(124, 49); }
                  break;
               case 125:
                  if (curChar == 10)
                     { jjCheckNAdd(123); }
                  break;
               case 129:
                  if (curChar == 10)
                     { jjCheckNAdd(128); }
                  break;
               case 132:
                  if (curChar == 10)
                     { jjCheckNAdd(42); }
                  break;
               case 135:
                  if (curChar == 10)
                     { jjCheckNAdd(35); }
                  break;
               case 139:
                  if (curChar == 10)
                     { jjCheckNAdd(138); }
                  break;
               case 143:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(143, 152); }
                  break;
               case 145:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(145, 146); }
                  break;
               case 146:
                  if (curChar == 34)
                     { jjCheckNAdd(147); }
                  break;
               case 147:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(147, 37); }
                  break;
               case 148:
                  if (curChar == 10)
                     { jjCheckNAdd(146); }
                  break;
               case 153:
                  if (curChar == 10)
                     { jjCheckNAdd(152); }
                  break;
               case 157:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(157, 165); }
                  break;
               case 159:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(159, 160); }
                  break;
               case 160:
                  if (curChar == 34)
                     { jjCheckNAdd(161); }
                  break;
               case 161:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(161, 37); }
                  break;
               case 162:
                  if (curChar == 10)
                     { jjCheckNAdd(160); }
                  break;
               case 166:
                  if (curChar == 10)
                     { jjCheckNAdd(165); }
                  break;
               case 169:
                  if (curChar == 10)
                     { jjCheckNAdd(30); }
                  break;
               case 177:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(177, 178); }
                  break;
               case 180:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(180, 286); }
                  break;
               case 182:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(182, 183); }
                  break;
               case 183:
                  if (curChar == 34)
                     { jjCheckNAdd(184); }
                  break;
               case 184:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(184, 185); }
                  break;
               case 185:
                  if (curChar == 34)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 186:
                  if ((0x100002200L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  { jjCheckNAdd(186); }
                  break;
               case 187:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(282, 244); }
                  break;
               case 189:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(189, 190); }
                  break;
               case 192:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(192, 249); }
                  break;
               case 194:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(194, 195); }
                  break;
               case 195:
                  if (curChar == 34)
                     { jjCheckNAdd(196); }
                  break;
               case 196:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(196, 197); }
                  break;
               case 197:
                  if (curChar == 34)
                     { jjCheckNAddStates(14, 16); }
                  break;
               case 199:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(199, 200); }
                  break;
               case 202:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(202, 211); }
                  break;
               case 204:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(204, 205); }
                  break;
               case 205:
                  if (curChar == 34)
                     { jjCheckNAdd(206); }
                  break;
               case 206:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(206, 207); }
                  break;
               case 207:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(186, 12); }
                  break;
               case 208:
                  if (curChar == 10)
                     { jjCheckNAdd(205); }
                  break;
               case 212:
                  if (curChar == 10)
                     { jjCheckNAdd(211); }
                  break;
               case 216:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(216, 225); }
                  break;
               case 218:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(218, 219); }
                  break;
               case 219:
                  if (curChar == 34)
                     { jjCheckNAdd(220); }
                  break;
               case 220:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(220, 207); }
                  break;
               case 221:
                  if (curChar == 10)
                     { jjCheckNAdd(219); }
                  break;
               case 226:
                  if (curChar == 10)
                     { jjCheckNAdd(225); }
                  break;
               case 230:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(230, 238); }
                  break;
               case 232:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(232, 233); }
                  break;
               case 233:
                  if (curChar == 34)
                     { jjCheckNAdd(234); }
                  break;
               case 234:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(234, 207); }
                  break;
               case 235:
                  if (curChar == 10)
                     { jjCheckNAdd(233); }
                  break;
               case 239:
                  if (curChar == 10)
                     { jjCheckNAdd(238); }
                  break;
               case 242:
                  if (curChar == 10)
                     { jjCheckNAdd(200); }
                  break;
               case 245:
                  if (curChar == 32)
                     { jjCheckNAdd(244); }
                  break;
               case 246:
                  if (curChar == 10)
                     { jjCheckNAdd(195); }
                  break;
               case 250:
                  if (curChar == 10)
                     { jjCheckNAdd(249); }
                  break;
               case 254:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(254, 263); }
                  break;
               case 256:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(256, 257); }
                  break;
               case 257:
                  if (curChar == 34)
                     { jjCheckNAdd(258); }
                  break;
               case 258:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(258, 197); }
                  break;
               case 259:
                  if (curChar == 10)
                     { jjCheckNAdd(257); }
                  break;
               case 264:
                  if (curChar == 10)
                     { jjCheckNAdd(263); }
                  break;
               case 268:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(268, 276); }
                  break;
               case 270:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(270, 271); }
                  break;
               case 271:
                  if (curChar == 34)
                     { jjCheckNAdd(272); }
                  break;
               case 272:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(272, 197); }
                  break;
               case 273:
                  if (curChar == 10)
                     { jjCheckNAdd(271); }
                  break;
               case 277:
                  if (curChar == 10)
                     { jjCheckNAdd(276); }
                  break;
               case 280:
                  if (curChar == 10)
                     { jjCheckNAdd(190); }
                  break;
               case 283:
                  if (curChar == 10)
                     { jjCheckNAdd(183); }
                  break;
               case 287:
                  if (curChar == 10)
                     { jjCheckNAdd(286); }
                  break;
               case 291:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(291, 300); }
                  break;
               case 293:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(293, 294); }
                  break;
               case 294:
                  if (curChar == 34)
                     { jjCheckNAdd(295); }
                  break;
               case 295:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(295, 185); }
                  break;
               case 296:
                  if (curChar == 10)
                     { jjCheckNAdd(294); }
                  break;
               case 301:
                  if (curChar == 10)
                     { jjCheckNAdd(300); }
                  break;
               case 305:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(305, 313); }
                  break;
               case 307:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(307, 308); }
                  break;
               case 308:
                  if (curChar == 34)
                     { jjCheckNAdd(309); }
                  break;
               case 309:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(309, 185); }
                  break;
               case 310:
                  if (curChar == 10)
                     { jjCheckNAdd(308); }
                  break;
               case 314:
                  if (curChar == 10)
                     { jjCheckNAdd(313); }
                  break;
               case 317:
                  if (curChar == 10)
                     { jjCheckNAdd(178); }
                  break;
               case 327:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(327, 328); }
                  break;
               case 330:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(330, 456); }
                  break;
               case 332:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(332, 333); }
                  break;
               case 333:
                  if (curChar == 34)
                     { jjCheckNAdd(334); }
                  break;
               case 334:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(334, 335); }
                  break;
               case 335:
                  if (curChar == 34)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 336:
                  if ((0x100002200L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  { jjCheckNAdd(336); }
                  break;
               case 337:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(452, 403); }
                  break;
               case 338:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 339;
                  break;
               case 341:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(341, 408); }
                  break;
               case 343:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(343, 344); }
                  break;
               case 344:
                  if (curChar == 34)
                     { jjCheckNAdd(345); }
                  break;
               case 345:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(345, 346); }
                  break;
               case 346:
                  if (curChar == 34)
                     { jjCheckNAddStates(20, 22); }
                  break;
               case 347:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 348;
                  break;
               case 350:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(350, 359); }
                  break;
               case 352:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(352, 353); }
                  break;
               case 353:
                  if (curChar == 34)
                     { jjCheckNAdd(354); }
                  break;
               case 354:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(354, 355); }
                  break;
               case 355:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(336, 12); }
                  break;
               case 356:
                  if (curChar == 10)
                     { jjCheckNAdd(353); }
                  break;
               case 360:
                  if (curChar == 10)
                     { jjCheckNAdd(359); }
                  break;
               case 364:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(364, 383); }
                  break;
               case 366:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(366, 367); }
                  break;
               case 367:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 368;
                  break;
               case 370:
                  if (curChar == 47)
                     { jjCheckNAdd(371); }
                  break;
               case 371:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(371, 355); }
                  break;
               case 372:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 370;
                  break;
               case 373:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 372;
                  break;
               case 380:
                  if (curChar == 10)
                     { jjCheckNAdd(367); }
                  break;
               case 384:
                  if (curChar == 10)
                     { jjCheckNAdd(383); }
                  break;
               case 388:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(388, 397); }
                  break;
               case 390:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(390, 391); }
                  break;
               case 391:
                  if (curChar == 34)
                     { jjCheckNAdd(392); }
                  break;
               case 392:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(392, 355); }
                  break;
               case 393:
                  if (curChar == 10)
                     { jjCheckNAdd(391); }
                  break;
               case 398:
                  if (curChar == 10)
                     { jjCheckNAdd(397); }
                  break;
               case 404:
                  if (curChar == 32)
                     { jjCheckNAdd(403); }
                  break;
               case 405:
                  if (curChar == 10)
                     { jjCheckNAdd(344); }
                  break;
               case 409:
                  if (curChar == 10)
                     { jjCheckNAdd(408); }
                  break;
               case 413:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(413, 432); }
                  break;
               case 415:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(415, 416); }
                  break;
               case 416:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 417;
                  break;
               case 419:
                  if (curChar == 47)
                     { jjCheckNAdd(420); }
                  break;
               case 420:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(420, 346); }
                  break;
               case 421:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 419;
                  break;
               case 422:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 421;
                  break;
               case 429:
                  if (curChar == 10)
                     { jjCheckNAdd(416); }
                  break;
               case 433:
                  if (curChar == 10)
                     { jjCheckNAdd(432); }
                  break;
               case 437:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(437, 446); }
                  break;
               case 439:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(439, 440); }
                  break;
               case 440:
                  if (curChar == 34)
                     { jjCheckNAdd(441); }
                  break;
               case 441:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(441, 346); }
                  break;
               case 442:
                  if (curChar == 10)
                     { jjCheckNAdd(440); }
                  break;
               case 447:
                  if (curChar == 10)
                     { jjCheckNAdd(446); }
                  break;
               case 453:
                  if (curChar == 10)
                     { jjCheckNAdd(333); }
                  break;
               case 457:
                  if (curChar == 10)
                     { jjCheckNAdd(456); }
                  break;
               case 461:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(461, 480); }
                  break;
               case 463:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(463, 464); }
                  break;
               case 464:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 465;
                  break;
               case 467:
                  if (curChar == 47)
                     { jjCheckNAdd(468); }
                  break;
               case 468:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(468, 335); }
                  break;
               case 469:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 467;
                  break;
               case 470:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 469;
                  break;
               case 477:
                  if (curChar == 10)
                     { jjCheckNAdd(464); }
                  break;
               case 481:
                  if (curChar == 10)
                     { jjCheckNAdd(480); }
                  break;
               case 485:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(485, 494); }
                  break;
               case 487:
                  if ((0x100002200L & l) != 0L)
                     { jjCheckNAddTwoStates(487, 488); }
                  break;
               case 488:
                  if (curChar == 34)
                     { jjCheckNAdd(489); }
                  break;
               case 489:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(489, 335); }
                  break;
               case 490:
                  if (curChar == 10)
                     { jjCheckNAdd(488); }
                  break;
               case 495:
                  if (curChar == 10)
                     { jjCheckNAdd(494); }
                  break;
               case 498:
                  if (curChar == 10)
                     { jjCheckNAdd(328); }
                  break;
               case 502:
                  if (curChar == 10)
                     { jjCheckNAddStates(23, 26); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 68)
                     { jjAddStates(27, 28); }
                  break;
               case 2:
                  if (curChar == 69)
                     { jjAddStates(29, 30); }
                  break;
               case 4:
                  if (curChar == 72)
                     { jjAddStates(31, 32); }
                  break;
               case 6:
                  if (curChar == 69)
                     { jjAddStates(33, 34); }
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjAddStates(35, 36); }
                  break;
               case 14:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 15:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 20:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 21:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 25:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 71)
                     { jjAddStates(37, 38); }
                  break;
               case 30:
                  if (curChar == 87)
                     { jjAddStates(39, 41); }
                  break;
               case 31:
                  if (curChar == 72)
                     { jjAddStates(42, 43); }
                  break;
               case 33:
                  if (curChar == 84)
                     { jjAddStates(44, 45); }
                  break;
               case 36:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(36, 37); }
                  break;
               case 40:
                  if (curChar == 68)
                     { jjAddStates(46, 47); }
                  break;
               case 42:
                  if (curChar == 87)
                     { jjAddStates(48, 50); }
                  break;
               case 43:
                  if (curChar == 72)
                     { jjAddStates(51, 52); }
                  break;
               case 45:
                  if (curChar == 84)
                     { jjAddStates(53, 54); }
                  break;
               case 48:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 50:
                  if (curChar == 68)
                     { jjAddStates(55, 56); }
                  break;
               case 52:
                  if (curChar == 87)
                     { jjAddStates(57, 59); }
                  break;
               case 53:
                  if (curChar == 72)
                     { jjAddStates(60, 61); }
                  break;
               case 55:
                  if (curChar == 84)
                     { jjAddStates(62, 63); }
                  break;
               case 58:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(58, 59); }
                  break;
               case 61:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 62:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 65:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 66:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 72)
                     { jjAddStates(64, 65); }
                  break;
               case 69:
                  if (curChar == 82)
                     { jjAddStates(66, 67); }
                  break;
               case 72:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(72, 59); }
                  break;
               case 74:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 75:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 79:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 80:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 72)
                     { jjAddStates(68, 69); }
                  break;
               case 83:
                  if (curChar == 84)
                     { jjAddStates(70, 71); }
                  break;
               case 86:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(86, 59); }
                  break;
               case 88:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 89:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 92:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 93:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 95:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 96:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 99:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 100:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 103:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 104:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 72)
                     { jjAddStates(72, 73); }
                  break;
               case 107:
                  if (curChar == 82)
                     { jjAddStates(74, 75); }
                  break;
               case 110:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(110, 49); }
                  break;
               case 112:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 113:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 117:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 118:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 72)
                     { jjAddStates(76, 77); }
                  break;
               case 121:
                  if (curChar == 84)
                     { jjAddStates(78, 79); }
                  break;
               case 124:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(124, 49); }
                  break;
               case 126:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 127:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 130:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 131:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 134:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 136:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 137:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 140:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 141:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 72)
                     { jjAddStates(80, 81); }
                  break;
               case 144:
                  if (curChar == 82)
                     { jjAddStates(82, 83); }
                  break;
               case 147:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(147, 37); }
                  break;
               case 149:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 150:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 155:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 72)
                     { jjAddStates(84, 85); }
                  break;
               case 158:
                  if (curChar == 84)
                     { jjAddStates(86, 87); }
                  break;
               case 161:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(161, 37); }
                  break;
               case 163:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 164:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 167:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 168:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 170:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 171:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 72)
                     { jjAddStates(88, 89); }
                  break;
               case 178:
                  if (curChar == 87)
                     { jjAddStates(90, 92); }
                  break;
               case 179:
                  if (curChar == 72)
                     { jjAddStates(93, 94); }
                  break;
               case 181:
                  if (curChar == 84)
                     { jjAddStates(95, 96); }
                  break;
               case 184:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(184, 185); }
                  break;
               case 188:
                  if (curChar == 68)
                     { jjAddStates(97, 98); }
                  break;
               case 190:
                  if (curChar == 87)
                     { jjAddStates(99, 101); }
                  break;
               case 191:
                  if (curChar == 72)
                     { jjAddStates(102, 103); }
                  break;
               case 193:
                  if (curChar == 84)
                     { jjAddStates(104, 105); }
                  break;
               case 196:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(196, 197); }
                  break;
               case 198:
                  if (curChar == 68)
                     { jjAddStates(106, 107); }
                  break;
               case 200:
                  if (curChar == 87)
                     { jjAddStates(108, 110); }
                  break;
               case 201:
                  if (curChar == 72)
                     { jjAddStates(111, 112); }
                  break;
               case 203:
                  if (curChar == 84)
                     { jjAddStates(113, 114); }
                  break;
               case 206:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(206, 207); }
                  break;
               case 209:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 210:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 213:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 214:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 72)
                     { jjAddStates(115, 116); }
                  break;
               case 217:
                  if (curChar == 82)
                     { jjAddStates(117, 118); }
                  break;
               case 220:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(220, 207); }
                  break;
               case 222:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 223:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 227:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 228:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 72)
                     { jjAddStates(119, 120); }
                  break;
               case 231:
                  if (curChar == 84)
                     { jjAddStates(121, 122); }
                  break;
               case 234:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(234, 207); }
                  break;
               case 236:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 237:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 240:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 241:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 243:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 244:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 247:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 248:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 251:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 252:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 72)
                     { jjAddStates(123, 124); }
                  break;
               case 255:
                  if (curChar == 82)
                     { jjAddStates(125, 126); }
                  break;
               case 258:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(258, 197); }
                  break;
               case 260:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 261:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 265:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 266:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 72)
                     { jjAddStates(127, 128); }
                  break;
               case 269:
                  if (curChar == 84)
                     { jjAddStates(129, 130); }
                  break;
               case 272:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(272, 197); }
                  break;
               case 274:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 275:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 278:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 279:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 281:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 282:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 284:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 285:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 288:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 289:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 290:
                  if (curChar == 72)
                     { jjAddStates(131, 132); }
                  break;
               case 292:
                  if (curChar == 82)
                     { jjAddStates(133, 134); }
                  break;
               case 295:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(295, 185); }
                  break;
               case 297:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 298:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 299:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 300:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 302:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 303:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 304:
                  if (curChar == 72)
                     { jjAddStates(135, 136); }
                  break;
               case 306:
                  if (curChar == 84)
                     { jjAddStates(137, 138); }
                  break;
               case 309:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(309, 185); }
                  break;
               case 311:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 312:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 313:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 315:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 316:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 318:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 319:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 320:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 321:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 320;
                  break;
               case 322:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 323:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 322;
                  break;
               case 324:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 325:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 324;
                  break;
               case 326:
                  if (curChar == 75)
                     { jjAddStates(139, 140); }
                  break;
               case 328:
                  if (curChar == 87)
                     { jjAddStates(141, 143); }
                  break;
               case 329:
                  if (curChar == 72)
                     { jjAddStates(144, 145); }
                  break;
               case 331:
                  if (curChar == 84)
                     { jjAddStates(146, 147); }
                  break;
               case 334:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(334, 335); }
                  break;
               case 339:
                  if (curChar == 87)
                     { jjAddStates(148, 150); }
                  break;
               case 340:
                  if (curChar == 72)
                     { jjAddStates(151, 152); }
                  break;
               case 342:
                  if (curChar == 84)
                     { jjAddStates(153, 154); }
                  break;
               case 345:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(345, 346); }
                  break;
               case 348:
                  if (curChar == 87)
                     { jjAddStates(155, 157); }
                  break;
               case 349:
                  if (curChar == 72)
                     { jjAddStates(158, 159); }
                  break;
               case 351:
                  if (curChar == 84)
                     { jjAddStates(160, 161); }
                  break;
               case 354:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(354, 355); }
                  break;
               case 357:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 351;
                  break;
               case 358:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 357;
                  break;
               case 359:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 358;
                  break;
               case 361:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 349;
                  break;
               case 362:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 361;
                  break;
               case 363:
                  if (curChar == 72)
                     { jjAddStates(162, 163); }
                  break;
               case 365:
                  if (curChar == 75)
                     { jjAddStates(164, 165); }
                  break;
               case 368:
                  if (curChar == 104)
                     { jjAddStates(166, 167); }
                  break;
               case 369:
                  if (curChar == 112)
                     { jjCheckNAdd(373); }
                  break;
               case 371:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(371, 355); }
                  break;
               case 374:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 369;
                  break;
               case 375:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 374;
                  break;
               case 376:
                  if (curChar == 115)
                     { jjCheckNAdd(373); }
                  break;
               case 377:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 376;
                  break;
               case 378:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 377;
                  break;
               case 379:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 378;
                  break;
               case 381:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 365;
                  break;
               case 382:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 381;
                  break;
               case 383:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 382;
                  break;
               case 385:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 363;
                  break;
               case 386:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 385;
                  break;
               case 387:
                  if (curChar == 72)
                     { jjAddStates(168, 169); }
                  break;
               case 389:
                  if (curChar == 82)
                     { jjAddStates(170, 171); }
                  break;
               case 392:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(392, 355); }
                  break;
               case 394:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 389;
                  break;
               case 395:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 394;
                  break;
               case 396:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 395;
                  break;
               case 397:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 396;
                  break;
               case 399:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 387;
                  break;
               case 400:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 399;
                  break;
               case 401:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 402:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 401;
                  break;
               case 403:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 402;
                  break;
               case 406:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 407:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 406;
                  break;
               case 408:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 407;
                  break;
               case 410:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 411:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 410;
                  break;
               case 412:
                  if (curChar == 72)
                     { jjAddStates(172, 173); }
                  break;
               case 414:
                  if (curChar == 75)
                     { jjAddStates(174, 175); }
                  break;
               case 417:
                  if (curChar == 104)
                     { jjAddStates(176, 177); }
                  break;
               case 418:
                  if (curChar == 112)
                     { jjCheckNAdd(422); }
                  break;
               case 420:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(420, 346); }
                  break;
               case 423:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 418;
                  break;
               case 424:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 423;
                  break;
               case 425:
                  if (curChar == 115)
                     { jjCheckNAdd(422); }
                  break;
               case 426:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 425;
                  break;
               case 427:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 426;
                  break;
               case 428:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 427;
                  break;
               case 430:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 414;
                  break;
               case 431:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 430;
                  break;
               case 432:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 431;
                  break;
               case 434:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 412;
                  break;
               case 435:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 434;
                  break;
               case 436:
                  if (curChar == 72)
                     { jjAddStates(178, 179); }
                  break;
               case 438:
                  if (curChar == 82)
                     { jjAddStates(180, 181); }
                  break;
               case 441:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(441, 346); }
                  break;
               case 443:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 438;
                  break;
               case 444:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 443;
                  break;
               case 445:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 444;
                  break;
               case 446:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 445;
                  break;
               case 448:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 436;
                  break;
               case 449:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 448;
                  break;
               case 450:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 451:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 450;
                  break;
               case 452:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 451;
                  break;
               case 454:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 455:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 454;
                  break;
               case 456:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 455;
                  break;
               case 458:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 459:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 458;
                  break;
               case 460:
                  if (curChar == 72)
                     { jjAddStates(182, 183); }
                  break;
               case 462:
                  if (curChar == 75)
                     { jjAddStates(184, 185); }
                  break;
               case 465:
                  if (curChar == 104)
                     { jjAddStates(186, 187); }
                  break;
               case 466:
                  if (curChar == 112)
                     { jjCheckNAdd(470); }
                  break;
               case 468:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(468, 335); }
                  break;
               case 471:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 466;
                  break;
               case 472:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 471;
                  break;
               case 473:
                  if (curChar == 115)
                     { jjCheckNAdd(470); }
                  break;
               case 474:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 473;
                  break;
               case 475:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 474;
                  break;
               case 476:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 475;
                  break;
               case 478:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 462;
                  break;
               case 479:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 478;
                  break;
               case 480:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 479;
                  break;
               case 482:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 460;
                  break;
               case 483:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 482;
                  break;
               case 484:
                  if (curChar == 72)
                     { jjAddStates(188, 189); }
                  break;
               case 486:
                  if (curChar == 82)
                     { jjAddStates(190, 191); }
                  break;
               case 489:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(489, 335); }
                  break;
               case 491:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 486;
                  break;
               case 492:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 491;
                  break;
               case 493:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 492;
                  break;
               case 494:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 493;
                  break;
               case 496:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 484;
                  break;
               case 497:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 496;
                  break;
               case 499:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 500:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 499;
                  break;
               case 501:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 500;
                  break;
               case 503:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 504:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 503;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 505 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   1, 27, 175, 325, 501, 38, 12, 39, 97, 38, 12, 186, 12, 187, 245, 186, 
   12, 336, 12, 337, 404, 336, 12, 27, 175, 325, 501, 1, 502, 3, 23, 5, 
   19, 7, 13, 9, 10, 29, 169, 141, 155, 168, 32, 139, 34, 135, 41, 132, 
   104, 118, 131, 44, 102, 46, 98, 51, 94, 66, 80, 93, 54, 64, 56, 60, 
   68, 78, 70, 73, 82, 91, 84, 87, 106, 116, 108, 111, 120, 129, 122, 125, 
   143, 153, 145, 148, 157, 166, 159, 162, 177, 317, 289, 303, 316, 180, 287, 182, 
   283, 189, 280, 252, 266, 279, 192, 250, 194, 246, 199, 242, 214, 228, 241, 202, 
   212, 204, 208, 216, 226, 218, 221, 230, 239, 232, 235, 254, 264, 256, 259, 268, 
   277, 270, 273, 291, 301, 293, 296, 305, 314, 307, 310, 327, 498, 459, 483, 497, 
   330, 457, 332, 453, 411, 435, 449, 341, 409, 343, 405, 362, 386, 400, 350, 360, 
   352, 356, 364, 384, 366, 380, 375, 379, 388, 398, 390, 393, 413, 433, 415, 429, 
   424, 428, 437, 447, 439, 442, 461, 481, 463, 477, 472, 476, 485, 495, 487, 490, 
};

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public GrammarTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public GrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 505; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x9L, 
};
static final long[] jjtoSkip = {
   0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[505];
    static private final int[] jjstateSet = new int[2 * 505];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
