package com.company;
/* GrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. GrammarTokenManager.java */



/** Token Manager. */
public class GrammarTokenManager implements GrammarConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
static private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(435, 0);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 436;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x100002600L & l) != 0L)
                     { jjAddStates(0, 3); }
                  break;
               case 3:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 5:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 7:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 8:
                  if (curChar == 34)
                     { jjCheckNAdd(9); }
                  break;
               case 9:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
               case 54:
               case 180:
               case 306:
                  if (curChar == 34)
                     { jjCheckNAdd(11); }
                  break;
               case 11:
                  if ((0x100002600L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 25:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 30:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if (curChar == 34)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 33:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(11, 34); }
                  break;
               case 34:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(115, 84); }
                  break;
               case 36:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 41:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if (curChar == 34)
                     { jjCheckNAdd(43); }
                  break;
               case 43:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(85, 11); }
                  break;
               case 46:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 51:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if (curChar == 34)
                     { jjCheckNAdd(53); }
                  break;
               case 53:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(53, 54); }
                  break;
               case 61:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 63:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if (curChar == 34)
                     { jjCheckNAdd(65); }
                  break;
               case 65:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(65, 54); }
                  break;
               case 73:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 75:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if (curChar == 34)
                     { jjCheckNAdd(77); }
                  break;
               case 77:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(77, 54); }
                  break;
               case 85:
                  if (curChar == 32)
                     { jjCheckNAdd(84); }
                  break;
               case 92:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 94:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 95:
                  if (curChar == 34)
                     { jjCheckNAdd(96); }
                  break;
               case 96:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(96, 44); }
                  break;
               case 104:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 106:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 107:
                  if (curChar == 34)
                     { jjCheckNAdd(108); }
                  break;
               case 108:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(108, 44); }
                  break;
               case 122:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 124:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if (curChar == 34)
                     { jjCheckNAdd(126); }
                  break;
               case 126:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(126, 33); }
                  break;
               case 134:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 136:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 137:
                  if (curChar == 34)
                     { jjCheckNAdd(138); }
                  break;
               case 138:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(138, 33); }
                  break;
               case 151:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 156:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 157:
                  if (curChar == 34)
                     { jjCheckNAdd(158); }
                  break;
               case 158:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(158, 159); }
                  break;
               case 159:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(11, 160); }
                  break;
               case 160:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(241, 210); }
                  break;
               case 162:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 167:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 168:
                  if (curChar == 34)
                     { jjCheckNAdd(169); }
                  break;
               case 169:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(169, 170); }
                  break;
               case 170:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(211, 11); }
                  break;
               case 172:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 177:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 178:
                  if (curChar == 34)
                     { jjCheckNAdd(179); }
                  break;
               case 179:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(179, 180); }
                  break;
               case 187:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 189:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
                  if (curChar == 34)
                     { jjCheckNAdd(191); }
                  break;
               case 191:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(191, 180); }
                  break;
               case 199:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 201:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 202:
                  if (curChar == 34)
                     { jjCheckNAdd(203); }
                  break;
               case 203:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(203, 180); }
                  break;
               case 211:
                  if (curChar == 32)
                     { jjCheckNAdd(210); }
                  break;
               case 218:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 220:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 221:
                  if (curChar == 34)
                     { jjCheckNAdd(222); }
                  break;
               case 222:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(222, 170); }
                  break;
               case 230:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 232:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 233:
                  if (curChar == 34)
                     { jjCheckNAdd(234); }
                  break;
               case 234:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(234, 170); }
                  break;
               case 248:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 250:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 251:
                  if (curChar == 34)
                     { jjCheckNAdd(252); }
                  break;
               case 252:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(252, 159); }
                  break;
               case 260:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 262:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 263:
                  if (curChar == 34)
                     { jjCheckNAdd(264); }
                  break;
               case 264:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(264, 159); }
                  break;
               case 279:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 394;
                  break;
               case 284:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 285:
                  if (curChar == 34)
                     { jjCheckNAdd(286); }
                  break;
               case 286:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(286, 287); }
                  break;
               case 287:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(11, 288); }
                  break;
               case 288:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(391, 348); }
                  break;
               case 289:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 290;
                  break;
               case 292:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 352;
                  break;
               case 294:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               case 295:
                  if (curChar == 34)
                     { jjCheckNAdd(296); }
                  break;
               case 296:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(296, 297); }
                  break;
               case 297:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(349, 11); }
                  break;
               case 298:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 299;
                  break;
               case 301:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 303:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 304:
                  if (curChar == 34)
                     { jjCheckNAdd(305); }
                  break;
               case 305:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(305, 306); }
                  break;
               case 313:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 315:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 316;
                  break;
               case 316:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 317;
                  break;
               case 319:
                  if (curChar == 47)
                     { jjCheckNAdd(320); }
                  break;
               case 320:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(320, 306); }
                  break;
               case 321:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 319;
                  break;
               case 322:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 321;
                  break;
               case 335:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 343;
                  break;
               case 337:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 338;
                  break;
               case 338:
                  if (curChar == 34)
                     { jjCheckNAdd(339); }
                  break;
               case 339:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(339, 306); }
                  break;
               case 349:
                  if (curChar == 32)
                     { jjCheckNAdd(348); }
                  break;
               case 356:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 374;
                  break;
               case 358:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 359;
                  break;
               case 359:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 360;
                  break;
               case 362:
                  if (curChar == 47)
                     { jjCheckNAdd(363); }
                  break;
               case 363:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(363, 297); }
                  break;
               case 364:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 362;
                  break;
               case 365:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 364;
                  break;
               case 378:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 386;
                  break;
               case 380:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 381;
                  break;
               case 381:
                  if (curChar == 34)
                     { jjCheckNAdd(382); }
                  break;
               case 382:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(382, 297); }
                  break;
               case 398:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 416;
                  break;
               case 400:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 401;
                  break;
               case 401:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 402;
                  break;
               case 404:
                  if (curChar == 47)
                     { jjCheckNAdd(405); }
                  break;
               case 405:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(405, 287); }
                  break;
               case 406:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 404;
                  break;
               case 407:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 406;
                  break;
               case 420:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 428;
                  break;
               case 422:
                  if ((0x100002600L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 423;
                  break;
               case 423:
                  if (curChar == 34)
                     { jjCheckNAdd(424); }
                  break;
               case 424:
                  if ((0x7ffc00100000000L & l) != 0L)
                     { jjCheckNAddTwoStates(424, 287); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 4:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 6:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjAddStates(4, 5); }
                  break;
               case 12:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 13:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 18:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 21:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 26:
                  if (curChar == 87)
                     { jjAddStates(6, 8); }
                  break;
               case 27:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 29:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 35:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 37:
                  if (curChar == 87)
                     { jjAddStates(9, 11); }
                  break;
               case 38:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 45:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 47:
                  if (curChar == 87)
                     { jjAddStates(12, 14); }
                  break;
               case 48:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 50:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(53, 54); }
                  break;
               case 55:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 56:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 59:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 62:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(65, 54); }
                  break;
               case 66:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 67:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 71:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 74:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(77, 54); }
                  break;
               case 78:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 79:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 82:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 84:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 86:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 87:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 90:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 93:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(96, 44); }
                  break;
               case 97:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 98:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 102:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 105:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(108, 44); }
                  break;
               case 109:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 110:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 113:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 115:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 117:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 120:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 123:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(126, 33); }
                  break;
               case 127:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 128:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 132:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 135:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(138, 33); }
                  break;
               case 139:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 140:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 143:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 145:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 152:
                  if (curChar == 87)
                     { jjAddStates(15, 17); }
                  break;
               case 153:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 155:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(158, 159); }
                  break;
               case 161:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 163:
                  if (curChar == 87)
                     { jjAddStates(18, 20); }
                  break;
               case 164:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 166:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(169, 170); }
                  break;
               case 171:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 173:
                  if (curChar == 87)
                     { jjAddStates(21, 23); }
                  break;
               case 174:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 176:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(179, 180); }
                  break;
               case 181:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 182:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 185:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 188:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(191, 180); }
                  break;
               case 192:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 193:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 197:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 200:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(203, 180); }
                  break;
               case 204:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 205:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 208:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 210:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 212:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 213:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 216:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 219:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(222, 170); }
                  break;
               case 223:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 224:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 228:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 231:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(234, 170); }
                  break;
               case 235:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 236:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 239:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 241:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 243:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 246:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 249:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(252, 159); }
                  break;
               case 253:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 254:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 258:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 261:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(264, 159); }
                  break;
               case 265:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 266:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 269:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 271:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 276:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 280:
                  if (curChar == 87)
                     { jjAddStates(24, 26); }
                  break;
               case 281:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 283:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(286, 287); }
                  break;
               case 290:
                  if (curChar == 87)
                     { jjAddStates(27, 29); }
                  break;
               case 291:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 293:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 294;
                  break;
               case 296:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(296, 297); }
                  break;
               case 299:
                  if (curChar == 87)
                     { jjAddStates(30, 32); }
                  break;
               case 300:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 302:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(305, 306); }
                  break;
               case 307:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 308:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 300;
                  break;
               case 311:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 310;
                  break;
               case 312:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 313;
                  break;
               case 314:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 315;
                  break;
               case 317:
                  if (curChar == 104)
                     { jjAddStates(33, 34); }
                  break;
               case 318:
                  if (curChar == 112)
                     { jjCheckNAdd(322); }
                  break;
               case 320:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(320, 306); }
                  break;
               case 323:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 318;
                  break;
               case 324:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 323;
                  break;
               case 325:
                  if (curChar == 115)
                     { jjCheckNAdd(322); }
                  break;
               case 326:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 325;
                  break;
               case 327:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 326;
                  break;
               case 328:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 327;
                  break;
               case 329:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 314;
                  break;
               case 330:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 329;
                  break;
               case 331:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 330;
                  break;
               case 332:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 312;
                  break;
               case 333:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 336:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 337;
                  break;
               case 339:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(339, 306); }
                  break;
               case 340:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               case 341:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 340;
                  break;
               case 342:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 341;
                  break;
               case 343:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 342;
                  break;
               case 344:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 345:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 344;
                  break;
               case 346:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 298;
                  break;
               case 347:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 346;
                  break;
               case 348:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 347;
                  break;
               case 350:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 293;
                  break;
               case 351:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 350;
                  break;
               case 352:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 351;
                  break;
               case 353:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 354:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 353;
                  break;
               case 355:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 356;
                  break;
               case 357:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 358;
                  break;
               case 360:
                  if (curChar == 104)
                     { jjAddStates(35, 36); }
                  break;
               case 361:
                  if (curChar == 112)
                     { jjCheckNAdd(365); }
                  break;
               case 363:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(363, 297); }
                  break;
               case 366:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 361;
                  break;
               case 367:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 366;
                  break;
               case 368:
                  if (curChar == 115)
                     { jjCheckNAdd(365); }
                  break;
               case 369:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 368;
                  break;
               case 370:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 369;
                  break;
               case 371:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 370;
                  break;
               case 372:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 357;
                  break;
               case 373:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 372;
                  break;
               case 374:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 373;
                  break;
               case 375:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 355;
                  break;
               case 376:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 375;
                  break;
               case 377:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 378;
                  break;
               case 379:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 380;
                  break;
               case 382:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(382, 297); }
                  break;
               case 383:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 379;
                  break;
               case 384:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 383;
                  break;
               case 385:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 384;
                  break;
               case 386:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 385;
                  break;
               case 387:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 377;
                  break;
               case 388:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 387;
                  break;
               case 389:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               case 390:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 389;
                  break;
               case 391:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 390;
                  break;
               case 392:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 393:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 392;
                  break;
               case 394:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 393;
                  break;
               case 395:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 396:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 395;
                  break;
               case 397:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 398;
                  break;
               case 399:
                  if (curChar == 75)
                     jjstateSet[jjnewStateCnt++] = 400;
                  break;
               case 402:
                  if (curChar == 104)
                     { jjAddStates(37, 38); }
                  break;
               case 403:
                  if (curChar == 112)
                     { jjCheckNAdd(407); }
                  break;
               case 405:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(405, 287); }
                  break;
               case 408:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 403;
                  break;
               case 409:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 408;
                  break;
               case 410:
                  if (curChar == 115)
                     { jjCheckNAdd(407); }
                  break;
               case 411:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 410;
                  break;
               case 412:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 411;
                  break;
               case 413:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 412;
                  break;
               case 414:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 399;
                  break;
               case 415:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 414;
                  break;
               case 416:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 415;
                  break;
               case 417:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 397;
                  break;
               case 418:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 417;
                  break;
               case 419:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 420;
                  break;
               case 421:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 422;
                  break;
               case 424:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(424, 287); }
                  break;
               case 425:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 421;
                  break;
               case 426:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 425;
                  break;
               case 427:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 426;
                  break;
               case 428:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 427;
                  break;
               case 429:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 419;
                  break;
               case 430:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 429;
                  break;
               case 431:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 432:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 431;
                  break;
               case 433:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 432;
                  break;
               case 434:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 435:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 434;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 436 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   23, 149, 277, 433, 9, 10, 120, 132, 143, 90, 102, 113, 59, 71, 82, 246, 
   258, 269, 216, 228, 239, 185, 197, 208, 396, 418, 430, 354, 376, 388, 311, 333, 
   345, 324, 328, 367, 371, 409, 413, 
};

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

    /** Constructor. */
    public GrammarTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public GrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 436; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x9L, 
};
static final long[] jjtoSkip = {
   0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[436];
    static private final int[] jjstateSet = new int[2 * 436];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
